### ISSUE TITLE
Upstream - Stripe is now v7.4 (with 7.5 in beta)

### ISSUE THREAD

**Issue by cmcconomyfwig** [bhch/async-stripe#11]
Hi bchc,

Thanks for publishing this project!

Regarding versions, please see https://github.com/stripe/stripe-python/tags

Stripe seems to be moving fast!  
Would appreciate knowing what cadence this project plans to keep up with (or whether this project is going dormant and it would be better to handle async externally).

**Comment by bhch** [comment]
Hi, the project will not go dormant. I'm using it in my own projects, so I do have incentive to keep maintaining it.

I'm planning to catch up to them in a couple of weeks.

> Stripe seems to be moving fast!

I do keep an eye on new stripe releases and I've found that most commits are about typing support.

They are incrementally adding typing support and also releasing new versions frequently.

But I don't think they've added any API related new features since v6.0.0. So, in that respect, the current version should satisfy most needs.

**Comment by cmcconomyfwig** [comment]
Thank you for the response - I appreciate the time you are taking to support this!
